version: '3.7'

networks:
  default:
    ipam:
      config:
        - subnet: 10.42.5.0/24

services:
  postgres:
    image: postgres:12.3-alpine
    env_file: .env
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart: always
  ui:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    env_file: .env
    networks:
      default:
        ipv4_address: 10.42.5.20
    depends_on:
      - postgres
      - api
    restart: always
  api:
    build: ./api
    env_file: .env
    networks:
      default:
        ipv4_address: 10.42.5.40
    restart: always
  adhoc:
    build: ./adhoc
    env_file: .env
    restart: always
