version: '3.7'

services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    env_file: .env
  ui:
    build: ./app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    env_file: .env
  api:
    build: ./api
    command: nodemon ./src
    ports:
      - '3003:3003'
    volumes:
      - ./api:/app
    env_file: .env
  adhoc:
    build: ./adhoc
    volumes:
      - ./adhoc:/app
    env_file: .env
