FROM node:18-alpine as build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --quiet

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
